# Get average data per game

In [1]:
cd ../..

/Users/guillaume_baquiast/Documents/tmp

In [2]:
import pandas as pd
from datetime import timedelta
from src.retreive_avg_game_data import retrieve_avg_game_data

Get pre-game (window of 30 minutes) data

In [7]:
df_metadata = pd.read_csv("data/champions_league_metadata.csv")
df_metadata["market_time"] = pd.to_datetime(df_metadata["market_time"], dayfirst=True)

timedelta_min = timedelta(minutes=-30)
timedelta_max = timedelta(minutes=0)

df_pre_game = retrieve_avg_game_data(df_metadata, timedelta_min=None, timedelta_max=None)

Retrieving info for Barcelona v Paris St-G
Retrieving info for RB Leipzig v Liverpool
Retrieving info for Sevilla v Dortmund
Retrieving info for Porto v Juventus
Game Porto v Juventus not processed because of missing path
Retrieving info for Lazio v Bayern Munich
Retrieving info for Atletico Madrid v Chelsea
Retrieving info for Atalanta v Real Madrid
Retrieving info for Mgladbach v Man City
Retrieving info for Real Madrid v Liverpool
Retrieving info for Man City v Dortmund
Retrieving info for Bayern Munich v Paris St-G
Retrieving info for Porto v Chelsea
Retrieving info for Real Madrid v Chelsea
Retrieving info for Paris St-G v Man City
Retrieving info for Dortmund v Sevilla
Retrieving info for Juventus v Porto
Retrieving info for Paris St-G v Barcelona
Retrieving info for Liverpool v RB Leipzig
Retrieving info for Man City v Mgladbach
Game Man City v Mgladbach not processed because of missing path
Retrieving info for Real Madrid v Atalanta
Game Real Madrid v Atalanta not processed because of missing path
Retrieving info for Bayern Munich v Lazio
Retrieving info for Chelsea v Atletico Madrid
Retrieving info for Chelsea v Porto
Retrieving info for Paris St-G v Bayern Munich
Retrieving info for Liverpool v Real Madrid
Retrieving info for Dortmund v Man City
Retrieving info for Man City v Paris St-G
Retrieving info for Chelsea v Real Madrid
Retrieving info for Man City v Chelsea
Game Man City v Chelsea not processed because of missing path

In [10]:
df_pre_game

,event_name,event_id,market_type,runner_name,ltp,total_matched,odd,proba
0,Barcelona v Paris St-G,30186199,ALT_TOTAL_GOALS,Over,18.531980,0.0,17.531980,0.446034
1,Barcelona v Paris St-G,30186199,ALT_TOTAL_GOALS,Under,2.852872,0.0,1.852872,0.591516
2,Barcelona v Paris St-G,30186199,ASIAN_HANDICAP,Barcelona,5.378175,0.0,4.378175,0.497411
3,Barcelona v Paris St-G,30186199,ASIAN_HANDICAP,Paris St-G,5.447655,0.0,4.447655,0.491408
4,Barcelona v Paris St-G,30186199,BOOKING_ODDS,25pts and Under,5.348276,0.0,4.348276,0.187522
...,...,...,...,...,...,...,...,...
667,Chelsea v Real Madrid,30464707,WIN_BOTH_HALVES,Yes,7.662222,0.0,6.662222,0.223466
668,Real Madrid v Chelsea,30429977,TO_QUALIFY,Chelsea,1.958563,0.0,0.958563,0.518409
669,Real Madrid v Chelsea,30429977,TO_QUALIFY,Real Madrid,2.113333,0.0,1.113333,0.485199
670,To Qualify,2568449,TO_QUALIFY,Chelsea,2.270909,0.0,1.270909,0.440542
671,To Qualify,2568449,TO_QUALIFY,Real Madrid,1.783636,0.0,0.783636,0.560669

In [11]:
df_pre_game.to_csv("./data/30_min_pre_game_data.csv", index=False)

# Explore / debug

In [6]:
from src.retreive_data import retrieve_game_data, preprocess_game_data


event_name = "Porto v Juventus"

market_paths = df_metadata[df_metadata["event_name" ]==event_name]["path"].tolist()

if not isinstance(market_paths[0], str):
    print(f"Game {event_name} not processed because of missing path")

data_dict = retrieve_game_data(market_paths)
#df_game = preprocess_game_data(data_dict)

Game Porto v Juventus not processed because of missing path

TypeError: stat: path should be string, bytes, os.PathLike or integer, not float

In [7]:
data_dict

{'event_name': [],
 'event_id': [],
 'market_type': [],
 'market_time': [],
 'open_date': [],
 'market_id': [],
 'publish_time': [],
 'runner_name': [],
 'ltp': [],
 'total_matched': [],
 'in_play': []}

In [21]:
df_game

,publish_time,market_type,runner_name,event_name,event_id,market_time,open_date,market_id,ltp,total_matched,in_play,odd,proba,time_from_game_start
33,2020-12-14 19:27:56.284,ALT_TOTAL_GOALS,Over,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,-86 days +23:27:56.284000
791,2020-12-14 22:30:09.156,ALT_TOTAL_GOALS,Over,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,-85 days +02:30:09.156000
1549,2020-12-15 14:19:00.804,ALT_TOTAL_GOALS,Over,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,-85 days +18:19:00.804000
2307,2020-12-15 17:57:13.237,ALT_TOTAL_GOALS,Over,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,-85 days +21:57:13.237000
3065,2020-12-18 03:49:05.247,ALT_TOTAL_GOALS,Over,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,-82 days +07:49:05.247000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525019,2021-03-09 22:40:51.202,WIN_BOTH_HALVES,Yes,NaN,NaN,NaT,NaT,NaN,3.9,NaN,NaN,2.9,0.25641,0 days 02:40:51.202000
1525777,2021-03-09 22:41:51.200,WIN_BOTH_HALVES,Yes,NaN,NaN,NaT,NaT,NaN,3.9,NaN,NaN,2.9,0.25641,0 days 02:41:51.200000
1526535,2021-03-09 22:42:29.802,WIN_BOTH_HALVES,Yes,NaN,NaN,NaT,NaT,NaN,3.9,NaN,NaN,2.9,0.25641,0 days 02:42:29.802000
1527293,2021-03-09 22:43:31.851,WIN_BOTH_HALVES,Yes,NaN,NaN,NaT,NaT,NaN,3.9,NaN,NaN,2.9,0.25641,0 days 02:43:31.851000
1528051,2021-03-09 22:43:58.903,WIN_BOTH_HALVES,Yes,NaN,NaN,NaT,NaT,NaN,3.9,NaN,NaN,2.9,0.25641,0 days 02:43:58.903000

In [23]:
df_game["event_name"].unique()

array([nan, 'Juventus v Porto', 'Porto v Juventus', 'To Qualify'],
      dtype=object)

In [27]:
df_game.groupby(["event_name", "event_id"]).count()

,,publish_time,market_type,runner_name,market_time,open_date,market_id,ltp,total_matched,in_play,odd,proba,time_from_game_start
event_name,event_id,,,,,,,,,,,,
Juventus v Porto,30295345,76138,76138,76138,76138,76138,76138,54072,76138,76138,54072,54072,76138
Porto v Juventus,30186279,182,182,182,182,182,182,178,182,182,178,178,182
To Qualify,2568449,20,20,20,20,20,20,20,20,20,20,20,20

In [22]:
market_paths

['/Users/guillaume_baquiast/Documents/tmp/data/BASIC/2021/Mar/9/30295345']

In [8]:
start_in_play_t = df_game[(df_game["in_play"] == True) & (df_game["market_type"]=="MATCH_ODDS")]["publish_time"].min()

In [10]:
start_in_play_t

Timestamp('2021-03-09 20:00:51.236000')

In [13]:
retrieve_avg_game_data(
    df_metadata[df_metadata["event_name"]==event_name],
    timedelta_min=None,
    timedelta_max=None
)

Retrieving info for Porto v Juventus

,event_name,event_id,market_type,runner_name,ltp,total_matched,odd,proba
0,Juventus v Porto,30295345,ALT_TOTAL_GOALS,Over,6.137255,0.0,5.137255,0.464199
1,Juventus v Porto,30295345,ALT_TOTAL_GOALS,Under,3.800309,0.0,2.800309,0.544639
2,Juventus v Porto,30295345,ASIAN_HANDICAP,Juventus,3.636880,0.0,2.636880,0.581643
3,Juventus v Porto,30295345,ASIAN_HANDICAP,Porto,40.472460,0.0,39.472460,0.374183
4,Juventus v Porto,30295345,BOOKING_ODDS,25pts and Under,6.675862,0.0,5.675862,0.151199
...,...,...,...,...,...,...,...,...
757,Juventus v Porto,30295345,WIN_BOTH_HALVES,Yes,3.816667,0.0,2.816667,0.262672
758,Porto v Juventus,30186279,TO_QUALIFY,Juventus,1.520889,0.0,0.520889,0.695572
759,Porto v Juventus,30186279,TO_QUALIFY,Porto,3.739773,0.0,2.739773,0.311898
760,To Qualify,2568449,TO_QUALIFY,Juventus,1.960000,0.0,0.960000,0.550849
761,To Qualify,2568449,TO_QUALIFY,Porto,12.868000,0.0,11.868000,0.454839

In [15]:
df_pre_game[df_pre_game["event_name"]==event_name]

,event_name,event_id,market_type,runner_name,ltp,total_matched,odd,proba
758,Porto v Juventus,30186279,TO_QUALIFY,Juventus,1.520889,0.0,0.520889,0.695572
759,Porto v Juventus,30186279,TO_QUALIFY,Porto,3.739773,0.0,2.739773,0.311898

In [22]:
df_game[
    (df_game["in_play"]==True) & (df_game["market_type"]=="MATCH_ODDS")]["publish_time"].min()

Timestamp('2021-03-09 20:00:51.236000')

In [23]:
df_game[
    (df_game["in_play"]==True)]["publish_time"].min()

Timestamp('2021-02-17 20:00:16.061000')

In [20]:
df_game[df_game["in_play"]==True]

,publish_time,market_type,runner_name,event_name,event_id,market_time,open_date,market_id,ltp,total_matched,in_play,odd,proba,time_from_game_start
1395932,2021-03-09 20:00:51.236,ALT_TOTAL_GOALS,Over,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507372,36.00,0.0,True,35.00,0.027778,20 days 00:00:51.236000
1395933,2021-03-09 20:00:51.236,ALT_TOTAL_GOALS,Over,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507372,1.07,0.0,True,0.07,0.934579,20 days 00:00:51.236000
1395934,2021-03-09 20:00:51.236,ALT_TOTAL_GOALS,Over,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507372,1.27,0.0,True,0.27,0.787402,20 days 00:00:51.236000
1395935,2021-03-09 20:00:51.236,ALT_TOTAL_GOALS,Over,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507372,1.49,0.0,True,0.49,0.671141,20 days 00:00:51.236000
1395936,2021-03-09 20:00:51.236,ALT_TOTAL_GOALS,Over,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507372,1.56,0.0,True,0.56,0.641026,20 days 00:00:51.236000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1436946,2021-03-09 20:49:51.179,WIN_BOTH_HALVES,Yes,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507293,3.90,0.0,True,2.90,0.256410,20 days 00:49:51.179000
1437778,2021-03-09 20:50:51.083,WIN_BOTH_HALVES,Yes,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507295,3.90,0.0,True,2.90,0.256410,20 days 00:50:51.083000
1449203,2021-03-09 21:04:51.263,WIN_BOTH_HALVES,Yes,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507295,3.90,0.0,True,2.90,0.256410,20 days 01:04:51.263000
1493824,2021-03-09 21:58:51.230,WIN_BOTH_HALVES,Yes,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507295,3.90,0.0,True,2.90,0.256410,20 days 01:58:51.230000
1495450,2021-03-09 22:00:51.168,WIN_BOTH_HALVES,Yes,Juventus v Porto,30295345,2021-03-09 20:00:27,2021-03-09 20:00:27,1.179507295,3.90,0.0,True,2.90,0.256410,20 days 02:00:51.168000

In [21]:
df_game.market_type.unique()

array(['ALT_TOTAL_GOALS', 'ASIAN_HANDICAP', 'BOOKING_ODDS',
       'BOTH_TEAMS_TO_SCORE', 'CLEAN_SHEET', 'CORNER_MATCH_BET',
       'CORNER_ODDS', 'CORRECT_SCORE', 'CORRECT_SCORE2', 'DOUBLE_CHANCE',
       'DRAW_NO_BET', 'ET_BTTS', 'ET_CORRECT_SCORE', 'ET_FH_OU_GOALS_05',
       'ET_FH_OU_GOALS_15', 'ET_HALF_TIME', 'ET_NEXT_GOAL',
       'ET_OU_GOALS_05', 'ET_OU_GOALS_15', 'ET_OU_GOALS_25',
       'ET_OU_GOALS_35', 'EXTRA_TIME', 'FIRST_GOAL_ODDS',
       'FIRST_GOAL_SCORER', 'FIRST_HALF_GOALS_05', 'FIRST_HALF_GOALS_15',
       'FIRST_HALF_GOALS_25', 'HALF_TIME', 'HALF_TIME_FULL_TIME',
       'HALF_TIME_SCORE', 'HAT_TRICKED_SCORED', 'MATCH_ODDS',
       'MATCH_ODDS_AND_BTTS', 'MATCH_ODDS_AND_OU_25',
       'MATCH_ODDS_AND_OU_35', 'ODD_OR_EVEN', 'OVER_UNDER_05',
       'OVER_UNDER_105_CORNR', 'OVER_UNDER_135_CORNR', 'OVER_UNDER_15',
       'OVER_UNDER_25', 'OVER_UNDER_25_CARDS', 'OVER_UNDER_35',
       'OVER_UNDER_35_CARDS', 'OVER_UNDER_45', 'OVER_UNDER_45_CARDS',
       'OVER_UNDER_55', 'OVER_UNDER_55_CORNR', 'OVER_UNDER_65',
       'OVER_UNDER_65_CARDS', 'OVER_UNDER_75', 'OVER_UNDER_85',
       'OVER_UNDER_85_CORNR', 'PENALTY_TAKEN', 'SCORE_CAST',
       'SENDING_OFF', 'SHOWN_A_CARD', 'TEAM_A_1', 'TEAM_A_2', 'TEAM_A_3',
       'TEAM_A_OVER_UNDER_05', 'TEAM_A_OVER_UNDER_15',
       'TEAM_A_OVER_UNDER_25', 'TEAM_A_WIN_TO_NIL', 'TEAM_B_1',
       'TEAM_B_2', 'TEAM_B_3', 'TEAM_B_OVER_UNDER_05',
       'TEAM_B_OVER_UNDER_15', 'TEAM_B_OVER_UNDER_25',
       'TEAM_B_WIN_TO_NIL', 'TO_QUALIFY', 'TO_SCORE',
       'TO_SCORE_2_OR_MORE', 'TO_SCORE_BOTH_HALVES', 'TO_SCORE_HATTRICK',
       'WIN_BOTH_HALVES'], dtype=object)

In [10]:
df_pre_game.to_csv("./data/30_min_pre_game_data.csv", index=False)